openapi: 3.0.0
info:
  title: Intake API
  version: 1.0.0
paths:
  /api/intake:
    post:
      summary: Submits a list of URLs for processing.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                urls:
                  type: array
                  items:
                    type: string
                    format: uri
      responses:
        '200':
          description: URLs successfully enqueued.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  submitted_count:
                    type: integer
        '400':
          description: Invalid input.
