openapi: 3.0.0
info:
  title: Card API
  version: 1.0.0
paths:
  /api/card/{id}:
    post:
      summary: Submits edits for a specific card.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                version:
                  type: integer
                edits:
                  type: object
                  properties:
                    title:
                      type: string
                    description:
                      type: string
                    author:
                      type: string
      responses:
        '200':
          description: Edits successfully saved.
        '400':
          description: Invalid input.
        '409':
          description: Conflict, the card has been updated since the edit session started.
